package com.crazy.portal.bean.customer.wsdl.visits1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * 
 *         
 *
 * This class was generated by Apache CXF 3.1.6
 * 2019-09-06T13:06:31.528+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://sap.com/xi/A1S/Global", name = "ManageAppointmentActivityIn")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ManageAppointmentActivityIn {

    @WebMethod(operationName = "MaintainBundle", action = "http://sap.com/xi/A1S/Global/ManageAppointmentActivityIn/MaintainBundleRequest")
    @WebResult(name = "AppointmentActivityBundleMaintainConfirmation_sync_V1", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "AppointmentActivityBundleMaintainConfirmation_sync_V1")
    public AppointmentActivityMaintainConfirmationBundleMessageSyncV1 maintainBundle(
            @WebParam(partName = "AppointmentActivityBundleMaintainRequest_sync_V1", name = "AppointmentActivityBundleMaintainRequest_sync_V1", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
                    AppointmentActivityMaintainRequestBundleMessageSyncV1 appointmentActivityBundleMaintainRequestSyncV1
    ) throws StandardFaultMessage_Exception;

    @WebMethod(operationName = "CheckMaintainBundle", action = "http://sap.com/xi/A1S/Global/ManageAppointmentActivityIn/CheckMaintainBundleRequest")
    @WebResult(name = "AppointmentEmailActivityConfirmationBundleCheckMaintainResponse_sync_V1", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "AppointmentEmailActivityConfirmationBundleCheckMaintainResponse_sync_V1")
    public AppointmentActivityMaintainConfirmationBundleMessageSyncV1 checkMaintainBundle(
            @WebParam(partName = "AppointmentActivityRequestBundleCheckMaintainQuery_sync_V1", name = "AppointmentActivityRequestBundleCheckMaintainQuery_sync_V1", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
                    AppointmentActivityMaintainRequestBundleMessageSyncV1 appointmentActivityRequestBundleCheckMaintainQuerySyncV1
    ) throws StandardFaultMessage_Exception;
}
