package com.crazy.portal.bean.customer.wsdl.customer.ws.detail;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2019-09-20T12:02:33.092+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://0003111061-one-off.sap.com/Y4R4GVT9Y_", name = "Y4R4GVT9Y_WS_ExtendCustomer")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Y4R4GVT9YWSExtendCustomer {

    @WebMethod(operationName = "Update", action = "http://0003111061-one-off.sap.com/Y4R4GVT9Y_/Y4R4GVT9Y_WS_ExtendCustomer/UpdateRequest")
    @WebResult(name = "BO_ExtendCustomerUpdateConfirmation_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "BO_ExtendCustomerUpdateConfirmation_sync")
    public BOExtendCustomerUpdateConfirmationMessageSync update(
            @WebParam(partName = "BO_ExtendCustomerUpdateRequest_sync", name = "BO_ExtendCustomerUpdateRequest_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
                    BOExtendCustomerUpdateRequestMessageSync boExtendCustomerUpdateRequestSync
    ) throws StandardFaultMessage_Exception;

    @WebMethod(operationName = "Read", action = "http://0003111061-one-off.sap.com/Y4R4GVT9Y_/Y4R4GVT9Y_WS_ExtendCustomer/ReadRequest")
    @WebResult(name = "BO_ExtendCustomerReadByIDResponse_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "BO_ExtendCustomerReadByIDResponse_sync")
    public BOExtendCustomerReadByIDResponseMessageSync read(
            @WebParam(partName = "BO_ExtendCustomerReadByIDQuery_sync", name = "BO_ExtendCustomerReadByIDQuery_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
                    BOExtendCustomerReadByIDQueryMessageSync boExtendCustomerReadByIDQuerySync
    ) throws StandardFaultMessage_Exception;

    @WebMethod(action = "http://0003111061-one-off.sap.com/Y4R4GVT9Y_/Y4R4GVT9Y_WS_ExtendCustomer/querySalesDataRequest")
    @WebResult(name = "BO_ExtendCustomerquerySalesDataSalesDataSimpleByConfirmation_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "BO_ExtendCustomerquerySalesDataSalesDataSimpleByConfirmation_sync")
    public BOExtendCustomerquerySalesDataSalesDataSimpleByConfirmationMessageSync querySalesData(
            @WebParam(partName = "BO_ExtendCustomerquerySalesDataSalesDataSimpleByRequest_sync", name = "BO_ExtendCustomerquerySalesDataSalesDataSimpleByRequest_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
                    BOExtendCustomerquerySalesDataSalesDataSimpleByRequestMessageSync boExtendCustomerquerySalesDataSalesDataSimpleByRequestSync
    ) throws StandardFaultMessage_Exception;

    @WebMethod(operationName = "Query_ExtendCustomerInfo", action = "http://0003111061-one-off.sap.com/Y4R4GVT9Y_/Y4R4GVT9Y_WS_ExtendCustomer/Query_ExtendCustomerInfoRequest")
    @WebResult(name = "BO_ExtendCustomerQuery_ExtendCustomerInfoSimpleByConfirmation_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "BO_ExtendCustomerQuery_ExtendCustomerInfoSimpleByConfirmation_sync")
    public BOExtendCustomerQueryExtendCustomerInfoSimpleByConfirmationMessageSync queryExtendCustomerInfo(
            @WebParam(partName = "BO_ExtendCustomerQuery_ExtendCustomerInfoSimpleByRequest_sync", name = "BO_ExtendCustomerQuery_ExtendCustomerInfoSimpleByRequest_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
                    BOExtendCustomerQueryExtendCustomerInfoSimpleByRequestMessageSync boExtendCustomerQueryExtendCustomerInfoSimpleByRequestSync
    ) throws StandardFaultMessage_Exception;

    @WebMethod(operationName = "Create", action = "http://0003111061-one-off.sap.com/Y4R4GVT9Y_/Y4R4GVT9Y_WS_ExtendCustomer/CreateRequest")
    @WebResult(name = "BO_ExtendCustomerCreateConfirmation_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "BO_ExtendCustomerCreateConfirmation_sync")
    public BOExtendCustomerCreateConfirmationMessageSync create(
            @WebParam(partName = "BO_ExtendCustomerCreateRequest_sync", name = "BO_ExtendCustomerCreateRequest_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
                    BOExtendCustomerCreateRequestMessageSync boExtendCustomerCreateRequestSync
    ) throws StandardFaultMessage_Exception;

    @WebMethod(operationName = "Query_EXT_Cust_AssetInfo", action = "http://0003111061-one-off.sap.com/Y4R4GVT9Y_/Y4R4GVT9Y_WS_ExtendCustomer/Query_EXT_Cust_AssetInfoRequest")
    @WebResult(name = "BO_ExtendCustomerQuery_EXT_Cust_AssetInfoAssetInfoSimpleByConfirmation_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "BO_ExtendCustomerQuery_EXT_Cust_AssetInfoAssetInfoSimpleByConfirmation_sync")
    public BOExtendCustomerQueryEXTCustAssetInfoAssetInfoSimpleByConfirmationMessageSync queryEXTCustAssetInfo(
            @WebParam(partName = "BOExtCustQueryEXTCustAssetInfoAssetInfoSimpleByRequest_sync", name = "BOExtCustQueryEXTCustAssetInfoAssetInfoSimpleByRequest_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
                    BOExtendCustomerQueryEXTCustAssetInfoAssetInfoSimpleByRequestMessageSync boExtCustQueryEXTCustAssetInfoAssetInfoSimpleByRequestSync
    ) throws StandardFaultMessage_Exception;
}
