
logging:
  config: classpath:logback-dev.xml


#java -Djava.security.krb5.conf=/Users/Bill/Desktop/krb5.ini -Dsun.security.krb5.debug=true -jar
app:
  ad-domain: AD-THREEAPE.CN
  service-principal: HTTP/addemo.ad-threeape.cn@AD-THREEAPE.CN
  keytab-location: /tmp/tomcat.keytab

spring:
  datasource:
    username: root
    password: ThreeApe!@#$2019
    url: jdbc:mysql://47.100.106.186:3306/portal?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
