spring:
  datasource:
    username: root
    password: bill
    url: jdbc:mysql://localhost:3306/portal?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver