logging:
  config: classpath:logback-sit.xml

app:
  ad-domain: THREEAPE.CN
  service-principal: HTTP/ad.threeape.cn@THREEAPE.CN
  keytab-location: C:\Users\Administrator\Desktop\tomcat.keytab

spring:
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: biao.chenit@qq.com #QQ邮箱
    password: ewennkedjtdebeca #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: Javen #可以任意
    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: ${spring.mail.username} #与上面的username保持一致


  datasource:
    username: root
    password: ThreeApe!@#$2019
    url: jdbc:mysql://47.100.106.186:3306/portal?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

file:
  path:
    thrid-push: /service/ftp/portal_file/push_thrid/announcement
    thrid-pull: /service/ftp/portal_file/pull_thrid/announcement
    local: /service/ftp/portal_file/local/announcement
    template: /service/ftp/portal_file/template

announcement:
  local-path: ${file.path.local}/announcement/

deliver:
  template-path: ${file.path.template}/deliver/