logging:
  config: classpath:logback-sit.xml

app:
  ad-domain: THREEAPE.CN
  service-principal: HTTP/ad.threeape.cn@THREEAPE.CN
  keytab-location: /Users/Bill/Desktop/tomcat.keytab
  krb5-config: /Users/Bill/Desktop/krb5.ini

spring:
  mail:
    host: smtp.spreadtrum.com
    port: 587
    username: CRM.Admin@UniSoC.com
    password: caCA$617
    protocol: smtp
    default-encoding: UTF-8


  datasource:
    username: root
    password: ThreeApe!@#$2019
    url: jdbc:mysql://47.100.106.186:3306/portal?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

file:
  path:
    root: /service/ftp/portal_file #公用基础路径
    root-local: ${file.path.root}/local #portal系统内文件地址入口
    root-thrid-push: ${file.path.root}/push_thrid #portal对接第三方文件出口地址
    root-thrid-pull: ${file.path.root}/pull_thrid #第三方传输文件至portal入口地址
    root-template: ${file.path.root}/template #portal功能模版文件地址
    announcement: #公告管理模块
      local: ${file.path.root-local}/announcement/
    deliver: #出货管理模块
      template: ${file.path.root-template}/deliver/
      push: ${file.path.root-thrid-push}/deliver/
      pull: ${file.path.root-thrid-pull}/deliver/
      local: ${file.path.root-local}/deliver/
    receive: #收货管理模块
      template: ${file.path.root-template}/receive/
      push: ${file.path.root-thrid-push}/receive/
      pull: ${file.path.root-thrid-pull}/receive/
      local: ${file.path.root-local}/receive/
    forecast:
      push: ${file.path.root-thrid-push}/forecast/
      pull: ${file.path.root-thrid-pull}/forecast/

ecc:
  api:
    url: https://e600180-hcioem.hcisbt.cn1.hana.ondemand.com
  auth:
    username: S0020469033
    password: CRM@Unisoc
ftp:
  host:
  port:
  username:
  password:
  path:
    handover:
      push: /handover/push/
      pull: /handover/pull/
    forecast:
      push: /bitest/upload/
      pull: /bitest/download/