
logging:
  config: classpath:logback-uat.xml

app:
  ad-domain: unisoc.com
  service-principal: HTTP/crmqa.unisoc.com@unisoc.com
  keytab-location: /home/crmpor/svc.crm.keytab

spring:
  datasource:
    username: crmportalqa
    password: Crm$20%My99
    url: jdbc:mysql://10.29.60.170:3306/crmportalqa?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

file:
  path:
    announcement:
      thrid-push: /service/ftp/portal_file/push_thrid/announcement/
      thrid-pull: /service/ftp/portal_file/pull_thrid/announcement/
      local: /home/crmpor/ftp/portal_file/local/announcement/
