logging:
  config: classpath:logback-dev.xml

app:
  ad-domain: THREEAPE.CN
  service-principal: HTTP/ad.threeape.cn@THREEAPE.CN
  keytab-location: C:\Users\Administrator\Desktop\tomcat.keytab

spring:
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: biao.chenit@qq.com #QQ邮箱
    password: ewennkedjtdebeca #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: Javen #可以任意
    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: ${spring.mail.username} #与上面的username保持一致

  datasource:
    username: root
    password: ThreeApe!@#$2019
    url: jdbc:mysql://47.100.106.186:3306/portal?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

file:
  path:
    root: /Users/lee/Documents/job_code/portal_file #公用基础路径
    root-local: ${file.path.root}/local #portal系统内文件地址入口
    root-thrid-push: ${file.path.root}/push_thrid #portal对接第三方文件出口地址
    root-thrid-pull: ${file.path.root}/pull_thrid #第三方传输文件至portal入口地址
    root-template: ${file.path.root}/template #portal功能模版文件地址
    announcement: #公告管理模块
      local: ${file.path.root-local}/announcement/
    deliver: #出货管理模块
      template: ${file.path.root-template}/deliver/
      push: ${file.path.root-thrid-push}/deliver/
      pull: ${file.path.root-thrid-pull}/deliver/
    receive: #收货管理模块
      template: ${file.path.root-template}/receive/
      push: ${file.path.root-thrid-push}/receive/
      pull: ${file.path.root-thrid-pull}/receive/

api:
  url:
    bi-test: https://e600180-hcioem.hcisbt.cn1.hana.ondemand.com/http/CONN
    mdm-product: https://e600180-hcioem.hcisbt.cn1.hana.ondemand.com/http/MDMProductMaster
    ecc-credit: https://e600180-hcioem.hcisbt.cn1.hana.ondemand.com:443/cxf/CUSTOMERCREDIT
