logging:
  config: classpath:logback-sit.xml

app:
  ad-domain: THREEAPE.CN
  service-principal: HTTP/ad.threeape.cn@THREEAPE.CN
  keytab-location: C:\Users\Administrator\Desktop\tomcat.keytab

spring:
  datasource:
    username: root
    password: ThreeApe!@#$2019
    url: jdbc:mysql://47.100.106.186:3306/portal?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

file:
  path:
    announcement:
      thrid-push: /service/ftp/portal_file/push_thrid/announcement/
      thrid-pull: /service/ftp/portal_file/pull_thrid/announcement/
      local: /home/crmpor/ftp/portal_file/local/announcement/