package com.crazy.portal.bean.order.wsdl.delivery.update;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2019-10-29T12:48:56.771+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "ZPortal_DeliveryChange", 
                  wsdlLocation = "file:/Users/weiying/Documents/project/zr_portal/wsdl2java/npwsdl/CPI_ZPortal_DeliveryChange_PRD_1.wsdl",
                  targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style") 
public class ZPortalDeliveryChange_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZPortal_DeliveryChange");
    public final static QName ZPortalDeliveryChange = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZPortal_DeliveryChange");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/weiying/Documents/project/zr_portal/wsdl2java/npwsdl/CPI_ZPortal_DeliveryChange_PRD_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZPortalDeliveryChange_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/weiying/Documents/project/zr_portal/wsdl2java/npwsdl/CPI_ZPortal_DeliveryChange_PRD_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZPortalDeliveryChange_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZPortalDeliveryChange_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZPortalDeliveryChange_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ZPortalDeliveryChange_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ZPortalDeliveryChange_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ZPortalDeliveryChange_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ZPortalDeliveryChange
     */
    @WebEndpoint(name = "ZPortal_DeliveryChange")
    public ZPortalDeliveryChange getZPortalDeliveryChange() {
        return super.getPort(ZPortalDeliveryChange, ZPortalDeliveryChange.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZPortalDeliveryChange
     */
    @WebEndpoint(name = "ZPortal_DeliveryChange")
    public ZPortalDeliveryChange getZPortalDeliveryChange(WebServiceFeature... features) {
        return super.getPort(ZPortalDeliveryChange, ZPortalDeliveryChange.class, features);
    }

}
