package com.crazy.portal.bean.order.wsdl.delivery.update;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2019-10-29T12:48:56.737+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", name = "ZPortal_DeliveryChange")
@XmlSeeAlso({ObjectFactory.class})
public interface ZPortalDeliveryChange {

    @WebMethod(operationName = "Zrfcsddeliverychange")
    @RequestWrapper(localName = "Zrfcsddeliverychange", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "npcxf.Zrfcsddeliverychange")
    @ResponseWrapper(localName = "ZrfcsddeliverychangeResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "npcxf.ZrfcsddeliverychangeResponse")
    public void zrfcsddeliverychange(
            @WebParam(name = "Deliverydate", targetNamespace = "")
                    String deliverydate,
            @WebParam(name = "Itype", targetNamespace = "")
                    String itype,
            @WebParam(name = "Sapdeliveryid", targetNamespace = "")
                    String sapdeliveryid,
            @WebParam(mode = WebParam.Mode.INOUT, name = "Titem", targetNamespace = "")
                    javax.xml.ws.Holder<TableOfZsdptdnitemchange> titem,
            @WebParam(mode = WebParam.Mode.OUT, name = "Resultmessage", targetNamespace = "")
                    javax.xml.ws.Holder<String> resultmessage,
            @WebParam(mode = WebParam.Mode.OUT, name = "Resulttype", targetNamespace = "")
                    javax.xml.ws.Holder<String> resulttype
    );
}
