package npcxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2019-09-08T20:24:35.203+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", name = "ZRFCSDPRICESIMULATE")
@XmlSeeAlso({ObjectFactory.class})
public interface ZRFCSDPRICESIMULATE {

    @WebMethod(operationName = "Zrfcsdpricesimulate")
    @RequestWrapper(localName = "Zrfcsdpricesimulate", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "npcxf.Zrfcsdpricesimulate_Type")
    @ResponseWrapper(localName = "ZrfcsdpricesimulateResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "npcxf.ZrfcsdpricesimulateResponse")
    public void zrfcsdpricesimulate(
        @WebParam(mode = WebParam.Mode.INOUT, name = "EtItems", targetNamespace = "")
        javax.xml.ws.Holder<TableOfZpricessimulateItemOut> etItems,
        @WebParam(name = "IsHeader", targetNamespace = "")
        npcxf.ZpricessimulateHeaderIn isHeader,
        @WebParam(mode = WebParam.Mode.INOUT, name = "ItItems", targetNamespace = "")
        javax.xml.ws.Holder<TableOfZpricessimulateItemIn> itItems,
        @WebParam(mode = WebParam.Mode.OUT, name = "EsHeader", targetNamespace = "")
        javax.xml.ws.Holder<ZpricessimulateHeaderOut> esHeader
    );
}
