package com.crazy.portal.bean.customer.wsdl.orgnation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * 
 *         
 *
 * This class was generated by Apache CXF 3.1.6
 * 2019-09-09T13:59:04.880+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://sap.com/xi/AP/FO/MOM/Global", name = "QueryOrganisationalUnitIn")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface QueryOrganisationalUnitIn {

    @WebMethod(operationName = "FindByID", action = "http://sap.com/xi/AP/FO/MOM/Global/QueryOrganisationalUnitIn/FindByIDRequest")
    @WebResult(name = "OrganisationalUnitByIDResponse_sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "OrganisationalUnitByIDResponse_sync")
    public OrganisationalUnitByIDResponseMessageSync findByID(
            @WebParam(partName = "OrganisationalUnitByIDQuery_Sync", name = "OrganisationalUnitByIDQuery_Sync", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
                    OrganisationalUnitByIDQueryMessageSync organisationalUnitByIDQuerySync
    ) throws StandardFaultMessage_Exception;
}
