package com.crazy.portal.bean.customer.wsdl.orgnation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2019-09-09T13:59:04.895+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "service", 
                  wsdlLocation = "file:/Users/weiying/Documents/project/zr_portal/wsdl2java/npwsdl/CPI_QueryOrganisationalUnitIn.wsdl",
                  targetNamespace = "http://sap.com/xi/AP/FO/MOM/Global") 
public class Service extends javax.xml.ws.Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://sap.com/xi/AP/FO/MOM/Global", "service");
    public final static QName BindingSOAP12 = new QName("http://sap.com/xi/AP/FO/MOM/Global", "binding_SOAP12");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/weiying/Documents/project/zr_portal/wsdl2java/npwsdl/CPI_QueryOrganisationalUnitIn.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/weiying/Documents/project/zr_portal/wsdl2java/npwsdl/CPI_QueryOrganisationalUnitIn.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns QueryOrganisationalUnitIn
     */
    @WebEndpoint(name = "binding_SOAP12")
    public QueryOrganisationalUnitIn getBindingSOAP12() {
        return super.getPort(BindingSOAP12, QueryOrganisationalUnitIn.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QueryOrganisationalUnitIn
     */
    @WebEndpoint(name = "binding_SOAP12")
    public QueryOrganisationalUnitIn getBindingSOAP12(WebServiceFeature... features) {
        return super.getPort(BindingSOAP12, QueryOrganisationalUnitIn.class, features);
    }

}
