package com.crazy.portal.bean.customer.wsdl.customer.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * 
 *         
 *
 * This class was generated by Apache CXF 3.1.6
 * 2019-09-18T16:12:54.784+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://sap.com/xi/A1S/Global", name = "ManageCustomerIn")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ManageCustomerIn {

    @WebMethod(operationName = "CheckMaintainBundle_V1", action = "http://sap.com/xi/A1S/Global/ManageCustomerIn/CheckMaintainBundle_V1Request")
    @WebResult(name = "CustomerBundleMaintenanceCheckConfirmation_sync_V1", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "CustomerBundleMaintenanceCheckConfirmation_sync_V1")
    public CustomerBundleMaintainConfirmationMessageSyncV1 checkMaintainBundleV1(
            @WebParam(partName = "CustomerBundleMaintenanceCheckRequest_sync_V1", name = "CustomerBundleMaintenanceCheckRequest_sync_V1", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
                    CustomerBundleMaintainRequestMessageSyncV1 customerBundleMaintenanceCheckRequestSyncV1
    ) throws StandardFaultMessage_Exception;

    @WebMethod(operationName = "MaintainBundle_V1", action = "http://sap.com/xi/A1S/Global/ManageCustomerIn/MaintainBundle_V1Request")
    @WebResult(name = "CustomerBundleMaintainConfirmation_sync_V1", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global", partName = "CustomerBundleMaintainConfirmation_sync_V1")
    public CustomerBundleMaintainConfirmationMessageSyncV1 maintainBundleV1(
            @WebParam(partName = "CustomerBundleMaintainRequest_sync_V1", name = "CustomerBundleMaintainRequest_sync_V1", targetNamespace = "http://sap.com/xi/SAPGlobal20/Global")
                    CustomerBundleMaintainRequestMessageSyncV1 customerBundleMaintainRequestSyncV1
    ) throws StandardFaultMessage_Exception;
}
