package com.crazy.portal.bean.customer.dealer.credit;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-08-01T23:58:35.141+08:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "ZPortal_customercredit",
                  wsdlLocation = "http://cln.spreadtrum.com:8000/sap/bc/srt/rfc/sap/zportal customer credit/800/zportal customer credit/zportal customer credit",
                  targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
public class ZPortalCustomercredit_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZPortal_customercredit");
    public final static QName ZPortalCustomercredit = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZPortal_customercredit");
    static {
        URL url = null;
        try {
            url = new URL("fhttp://cln.spreadtrum.com:8000/sap/bc/srt/rfc/sap/zportal customer credit/800/zportal customer credit/zportal customer credit");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZPortalCustomercredit_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://cln.spreadtrum.com:8000/sap/bc/srt/rfc/sap/zportal customer credit/800/zportal customer credit/zportal customer credit");
        }
        WSDL_LOCATION = url;
    }

    public ZPortalCustomercredit_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZPortalCustomercredit_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZPortalCustomercredit_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ZPortalCustomercredit_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ZPortalCustomercredit_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ZPortalCustomercredit_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ZPortalCustomercredit
     */
    @WebEndpoint(name = "ZPortal_customercredit")
    public ZPortalCustomercredit getZPortalCustomercredit() {
        return super.getPort(ZPortalCustomercredit, ZPortalCustomercredit.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZPortalCustomercredit
     */
    @WebEndpoint(name = "ZPortal_customercredit")
    public ZPortalCustomercredit getZPortalCustomercredit(WebServiceFeature... features) {
        return super.getPort(ZPortalCustomercredit, ZPortalCustomercredit.class, features);
    }

}
